# One-shot deploy for the PharmaCenter Quote app (and the formula,
# meeting and order subdomains the same deployment serves).
#
# Usage from PowerShell in this folder:
#   .\deploy.ps1 "short description of the change"
#   .\deploy.ps1                    # prompts, rather than reusing a stale message
#   .\deploy.ps1 -SkipTypecheck "..." # emergency escape hatch, avoid
#
# It typechecks first and refuses to commit if that fails, then stages,
# commits, rebases over origin/main and pushes. Vercel builds in ~60s.
#
# A commit message is REQUIRED. Generated messages are how this project ended
# up with eight consecutive commits reading "workflow: gummy formula
# calculator (Bulk -> Gummy -> PC)" -- that stretch of history cannot be
# bisected. `git log` is only worth having if the messages are.
#
# THIS REPO IS THE SOURCE OF TRUTH -- edit files here.
#
# History: this app used to be edited in C:\q, with the git checkout as a
# disposable robocopy mirror of it. That mirror was copy-only (robocopy /E,
# no /PURGE, so deletions never propagated), carried an exclude list that
# silently dropped some files, and -- worst -- overwrote any edit made in
# the checkout on the next deploy, with no warning. C:\q was retired on
# 2026-09-19; the checkout already contained everything the mirror fed it.
# Do not reintroduce a mirror step. If anything still writes into C:\q,
# those changes will NOT reach production.

param(
    [switch] $SkipTypecheck,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]] $Message
)

$ErrorActionPreference = "Stop"

$msg = if ($Message) { $Message -join " " } else { Read-Host "Commit message" }
if (-not $msg) { Write-Error "A commit message is required."; exit 1 }

# --- Typecheck gate ---------------------------------------------------------
# Nothing here used to compile the code before it was pushed. Vercel's build
# was the first thing that ever typechecked it, so a type error cost a push,
# a wait, and a dashboard check to discover -- and `deploy.ps1` would report
# success on a commit that never became a deployment.
#
# This runs BEFORE `git add`, so a failure leaves the working tree exactly as
# it was. Nothing is staged, committed or pushed.
#
# Both repos typechecked clean when this gate was added (2026-09-19), so a
# failure here means something you just changed, not pre-existing debt.
if (-not $SkipTypecheck) {
    if (-not (Get-Command npx -ErrorAction SilentlyContinue)) {
        Write-Host "npx not found - skipping typecheck. Install Node to enable it." -ForegroundColor Yellow
    } else {
        if (-not (Test-Path "$PSScriptRoot\node_modules")) {
            # First run on a fresh clone. ~1-2 minutes, once.
            #
            # `npm ci` REQUIRES a lockfile and errors out without one. This repo
            # has never had a committed package-lock.json, so the original
            # `npm ci` here could not succeed on any fresh clone -- which meant
            # the typecheck gate added in H7 was silently un-runnable from the
            # day it shipped. Found 2026-09-20, the first time anyone deployed
            # from a tree with no node_modules.
            #
            # npm install writes a lockfile as a side effect, and `git add -A`
            # below commits it. After the first successful run this branch
            # takes the `npm ci` path for good, which is the reproducible one.
            $lock = Join-Path $PSScriptRoot "package-lock.json"
            Push-Location $PSScriptRoot
            if (Test-Path $lock) {
                Write-Host "node_modules missing - running npm ci (one-time, ~1-2 min)..." -ForegroundColor Cyan
                npm ci
            } else {
                Write-Host "node_modules and package-lock.json both missing - running npm install (~1-2 min)." -ForegroundColor Cyan
                Write-Host "The lockfile it generates will be committed, so this is the last time." -ForegroundColor DarkGray
                npm install
            }
            $ciCode = $LASTEXITCODE
            Pop-Location
            if ($ciCode -ne 0) { Write-Error "Dependency install failed - cannot typecheck."; exit 1 }
        }
        # next-env.d.ts is gitignored and generated by `next dev`/`next build`,
        # neither of which may have run here. Without it tsc cannot see Next's
        # ambient types. Writing it is exactly what Next itself does.
        $nextEnv = Join-Path $PSScriptRoot "next-env.d.ts"
        if (-not (Test-Path $nextEnv)) {
            Set-Content -Path $nextEnv -Encoding ASCII -Value @(
                '/// <reference types="next" />',
                '/// <reference types="next/image-types/global" />'
            )
        }
        Write-Host "Typechecking..." -ForegroundColor Cyan
        Push-Location $PSScriptRoot
        npx tsc -p tsconfig-check.json --noEmit
        $tscCode = $LASTEXITCODE
        Pop-Location
        if ($tscCode -ne 0) {
            Write-Host ""
            Write-Host "TYPECHECK FAILED - nothing staged, committed or pushed." -ForegroundColor Red
            Write-Host "Fix the errors above, then run deploy again." -ForegroundColor Red
            Write-Host "To deploy anyway (you almost never want this): .\deploy.ps1 -SkipTypecheck ""msg""" -ForegroundColor DarkGray
            exit 1
        }
        Write-Host "Typecheck passed." -ForegroundColor Green
    }
}
# A zero-byte .git/index.lock left behind by a crashed git process blocks
# every subsequent `git add`. Git writes this file and renames it within
# milliseconds, so a zero-byte lock more than 10 minutes old is debris, never
# a live operation.
#
# Hit twice on 2026-09-20. The second time it cost a whole deploy, and the way
# it cost it is the part worth fixing: `git add -A` failed, nothing was
# staged, and the check below then printed "Nothing to commit." and exited 0.
# A hard failure wearing the costume of a clean no-op -- the same shape as the
# C4 auto-updater, and as a deploy that reports success on a commit Vercel
# never built.
$lockFile = Join-Path $PSScriptRoot ".git\index.lock"
if (Test-Path $lockFile) {
    $lock = Get-Item $lockFile -Force
    $ageMin = ([DateTime]::Now - $lock.LastWriteTime).TotalMinutes
    if ($lock.Length -eq 0 -and $ageMin -gt 10) {
        Write-Host ("Removing stale .git/index.lock - 0 bytes, {0:N0} min old." -f $ageMin) -ForegroundColor Yellow
        Remove-Item $lockFile -Force
    } else {
        Write-Error ("A git process is holding .git/index.lock ({0} bytes, {1:N0} min old). Close any running git or editor operation, then retry." -f $lock.Length, $ageMin)
        exit 1
    }
}

git add -A
if ($LASTEXITCODE -ne 0) {
    Write-Error "git add failed - nothing staged, nothing committed, nothing pushed."
    exit 1
}
$staged = git diff --cached --name-only
if (-not $staged) {
    Write-Host "Nothing to commit." -ForegroundColor Yellow
    exit 0
}

Write-Host ""
Write-Host "Deploying $(@($staged).Count) file(s):" -ForegroundColor Cyan
$staged | Select-Object -First 20 | ForEach-Object { Write-Host "    $_" }
if (@($staged).Count -gt 20) { Write-Host "    ... and $(@($staged).Count - 20) more" }

git commit -m $msg
if ($LASTEXITCODE -ne 0) { Write-Error "git commit failed - nothing pushed."; exit 1 }
# Rebase over anything pushed from elsewhere (another chat, the GitHub UI,
# another machine) so a stale local main can't turn a deploy into a rejected
# push.
git pull --rebase origin main
git push
if ($LASTEXITCODE -ne 0) { Write-Error "git push FAILED - this deploy did not ship."; exit 1 }

Write-Host ""
Write-Host "Pushed. Vercel is rebuilding - give it ~60s." -ForegroundColor Green
Write-Host "A push is not a deployment: check the Vercel dashboard before" -ForegroundColor DarkGray
Write-Host "believing it shipped. An invalid vercel.json produces no" -ForegroundColor DarkGray
Write-Host "deployment record at all, which looks exactly like success here." -ForegroundColor DarkGray
