-- AI-generated key-points synthesis per SO. Combines Fishbowl live
-- state, Monday activity, and Plaud meeting notes into 3-5 bullets a
-- meeting reviewer can scan in seconds.
--
-- Generated by a Cowork scheduled task that calls Claude with the
-- per-SO context blob from GET /api/sync/so-synthesis/inputs, then
-- POSTs the resulting bullets to /api/sync/so-synthesis (bearer auth).

create table if not exists public.so_synthesis (
  so_number     text primary key,
  headline      text,                              -- optional 1-line summary
  points        jsonb not null default '[]'::jsonb, -- [{text: string, source?: string}]
  based_on      jsonb,                             -- provenance stamps used to generate
  generated_at  timestamptz not null default now()
);

create index if not exists so_synthesis_generated_idx
  on public.so_synthesis (generated_at desc);

alter table public.so_synthesis enable row level security;

drop policy if exists "so_synthesis read for authenticated" on public.so_synthesis;
create policy "so_synthesis read for authenticated"
  on public.so_synthesis for select
  to authenticated
  using (true);
